USE AppointmentCI;

CREATE TABLE [dbo].[Schedule] (
  [RefNo] nvarchar(10) COLLATE Thai_CI_AS  NULL,
  [Studykey] int  NULL,
  [HN] nvarchar(15) COLLATE Thai_CI_AS  NULL,
  [ThaiName] nvarchar(50) COLLATE Thai_CI_AS  NULL,
  [EngName] nvarchar(50) COLLATE Thai_CI_AS  NULL,
  [Age] nvarchar(3) COLLATE Thai_CI_AS  NULL,
  [Sex] nvarchar(2) COLLATE Thai_CI_AS  NULL,
  [Birthdate] nvarchar(8) COLLATE Thai_CI_AS  NULL,
  [Type] nvarchar(80) COLLATE Thai_CI_AS  NULL,
  [IPD_OPD] nvarchar(10) COLLATE Thai_CI_AS  NULL,
  [Location] nvarchar(50) COLLATE Thai_CI_AS  NULL,
  [LocationList] nvarchar(1000) COLLATE Thai_CI_AS  NULL,
  [Room] nvarchar(20) COLLATE Thai_CI_AS  NULL,
  [Modality] nvarchar(50) COLLATE Thai_CI_AS  NULL,
  [Bodypart] nvarchar(50) COLLATE Thai_CI_AS  NULL,
  [StudyDate] datetime  NULL,
  [StudyStart] nvarchar(10) COLLATE Thai_CI_AS  NULL,
  [StudyDuration] nvarchar(10) COLLATE Thai_CI_AS  NULL,
  [Cost] nvarchar(10) COLLATE Thai_CI_AS  NULL,
  [Note] nvarchar(4000) COLLATE Thai_CI_AS  NULL,
  [Event] nvarchar(4000) COLLATE Thai_CI_AS  NULL,
  [Status] nvarchar(50) COLLATE Thai_CI_AS  NULL,
  [InsertDT] datetime  NULL,
  [ModifiedDT] datetime  NULL,
  [ArrivalDT] datetime  NULL,
  [StartedDT] datetime  NULL,
  [CompleteDT] datetime  NULL,
  [Phone1] nvarchar(20) COLLATE Thai_CI_AS  NULL,
  [phone2] nvarchar(20) COLLATE Thai_CI_AS  NULL,
  [phone3] nvarchar(20) COLLATE Thai_CI_AS  NULL,
  [icon1] nvarchar(3) COLLATE Thai_CI_AS  NULL,
  [icon2] nvarchar(3) COLLATE Thai_CI_AS  NULL,
  [icon3] nvarchar(3) COLLATE Thai_CI_AS  NULL,
  [RecordStaff] nvarchar(50) COLLATE Thai_CI_AS  NULL
);